package irc

const (
	Pass     string = "PASS"
	Nick     string = "NICK"
	User     string = "USER"
	Oper     string = "OPER"
	Mode     string = "MODE"
	Service  string = "SERVICE"
	Quit     string = "QUIT"
	Squit    string = "SQUIT"
	Join     string = "JOIN"
	Part     string = "PART"
	Topic    string = "TOPIC"
	Names    string = "NAMES"
	List     string = "LIST"
	Invite   string = "INVITE"
	Kick     string = "KICK"
	Privmsg  string = "PRIVMSG"
	Notice   string = "NOTICE"
	Motd     string = "MOTD"
	Lusers   string = "LUSERS"
	Version  string = "VERSION"
	Stats    string = "STATS"
	Links    string = "LINKS"
	Time     string = "TIME"
	Connect  string = "CONNECT"
	Trace    string = "TRACE"
	Admin    string = "ADMIN"
	Info     string = "INFO"
	Servlist string = "SERVLIST"
	Squery   string = "SQUERY"
	Who      string = "WHO"
	Whois    string = "WHOIS"
	Whowas   string = "WHOWAS"
	Kill     string = "KILL"
	Ping     string = "PING"
	Pong     string = "PONG"
	Error    string = "ERROR"
	Away     string = "AWAY"
	Die      string = "DIE"
	Restart  string = "RESTART"
	Summon   string = "SUMMON"
	Users    string = "USERS"
	Wallops  string = "WALLOPS"
	Userhost string = "USERHOST"
	Ison     string = "ISON"
)
